import os 
from groq import Groq

class GroqLLMClient:
    def __init__(self, api_key):

        """
        Initialize the GroqLLMClient class.
        Args:
            api_key (str): The API key for the Groq API. 
        """
        
        if not api_key:
            api_key = os.environ.get("GROQ_API_KEY")
            if not api_key:
                raise ValueError("API key is required.")
        
        self.client = Groq(api_key = api_key)
    
    def chat_completion(self, prompt: str, model: str = "llama-3.3-70b-versatile", stream: bool = False) -> str:
        # """
        # Generate a chat completion using the Groq API.
        # Args:
        #     prompt (str): The input prompt for the chat completion.
        #     model (str): The model name for the chat completion (default: 'llama-3.3-70b-versatile').
        #     stream (bool): Whether to stream the response (default: False).
        # Returns:
        #     str: The chat completion generated by the Groq API.
        # """
        
        response = self.client.chat.completions.create(
            messages = [
                {
                    "role": "user", 
                    "content": prompt,
                }
            ],
            model = model,
            stream = stream,
        )

        return response.choices[0].message.content

